### PR TITLE
Update workingFit-workflow branch

### PR DESCRIPTION
**Pull request by sarafiorendi**
- Update the files common with basicMacroImplementation branch
- Add year as input option to the other files
- update readme file

NB. For plotEff.cc, for now only add the year option.
Another [PR](https://github.com/CMSKStarMuMu/eff-KDE/pull/3) to the basicMacroImplementation branch is already in place to fix the drawing of the slices for WT events.

After this PR is merged, the idea is to merge the working-fitWorkflow branch with the basicMacroImplementation one.

### CODE REVIEW

**Comment by aboletti** [comment]
General question:
here you apply the same changes that were applied in the `basicMacroImplementation` branch in [this PR](2), using different commits.
Will this create problems during the merging of `basicMacroImplementation` and `fitWorkflow`? Or just some conflicts that can be solved?

**Comment by aboletti** [comment]
I reviewed the changes to all the new files (not present in `basicMacroImplementation`) and they are fine for me.
Let's decide what to do with the other changes, then I think we can merge.

**Comment by sarafiorendi** [comment]
> General question:
> here you apply the same changes that were applied in the `basicMacroImplementation` branch in [this PR](2), using different commits.
> Will this create problems during the merging of `basicMacroImplementation` and `fitWorkflow`? Or just some conflicts that can be solved?

I think that different commits leading to the same code will not create problems (hopefully)

**Comment by aboletti** [comment]
Ok, let's try

**Pull request merged**
